# Generated by Django 5.2.8 on 2025-11-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_personaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='document_scan_back',
            field=models.FileField(blank=True, null=True, upload_to='docs/private/', verbose_name='Скан документа (обратная)'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='document_scan_front',
            field=models.FileField(blank=True, null=True, upload_to='docs/private/', verbose_name='Скан документа (лицевая)'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='manager_comment',
            field=models.TextField(blank=True, verbose_name='Коммент менеджера (если отказ)'),
        ),
    ]
