# Generated by Django 5.2.8 on 2025-11-26 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_subscriptionplan_profile_subscription_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_photos/')),
                ('date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена входа')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('participants', models.ManyToManyField(blank=True, related_name='attended_events', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('required_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.subscriptionplan', verbose_name='Минимальный тариф')),
            ],
        ),
    ]
